### ISSUE TITLE
Function equivalent to PT_RESTART?

### ISSUE THREAD

**Issue by sidlauskaslukas** [bxparks/AceRoutine#13]
Hi,

Does AceRoutine has a proper way to restart a COROUTINE?

**Comment by bxparks** [comment]
Hi,
Are you referring to:
* http://contiki.sourceforge.net/docs/2.6/a01802.html#gacd3ac045f0a4ae63412e3b3d8780e8ab
* http://dunkels.com/adam/pt/api.html
?

This is not provided. I have not needed it, and I thought that it would be too brittle to use correctly if static variables are used inside coroutines. However, since you are the second person to ask about this feature, maybe it's a useful feature to add.

I don't have much spare time these days, but I may be able to review a PR request for this feature.

**Comment by sidlauskaslukas** [comment]
@bxparks yes, I'm referring to these references
