### ISSUE TITLE
Examples don't set LED pinMode

### ISSUE THREAD

**Issue by mkarliner** [bxparks/AceRoutine#5]
In examples such as HelloCoroutine, the led does not flash as its pinMode has not been set to 
OUTPUT. At least, that is the case on a clone ATMega2650.

Separately, I'm probably being very stupid, but in examples such as HelloCoroutine, I would have
expected say, printHello to be run again when it has completed  rather than as a one shot. 
Am I missing something?

**Comment by bxparks** [comment]
Thanks for the report!

Seems like on the Arduino Nano, the `pinMode(LED, OUTPUT)` is not needed, but you are correct, it should be set. I updated the code.

The `printHello` coroutine contains a `COROUTINE_END()` macro. This causes the coroutine to run just once. (Essentially, each time it is called again from `loop()`, the control flow jumps directly to the `COROUTINE_END()`, bypassing everything above it.) A `COROUTINE_LOOP()` macro causes the coroutine routine to run forever, until you manually break out of it.

**Comment by mkarliner** [comment]
Does this mean that I can only run coroutines without a loop once? This is probably a RTFM, but it wasn't immediately obvious to me.

You may want to start a forum, I don't want to pollute github issues with my and others stupid questions.
FWIW, this exactly hits the spot for me, between COSA and the naive solutions, I hope it is very successful.

**Comment by bxparks** [comment]
If you are familiar with threads, a coroutine is conceptually similar. It starts up, executes, then finishes. The issue you might be having trouble with is that AceRoutine does not support dynamic creation of coroutines (because I don't to create anything on the heap, having only only 2kB of RAM on a small AVR Arduino), so the coroutine is created statically with the `COROUTINE()` macro. It executes (conceptually) immediately at the `COROUTINE_START()` position, then it finishes when it reaches the end of the `COROUTINE_END()`.  I tried to explain all this in the README.md. Let me know if something can be better explained.

With regards to starting a forum... where? On https://forum.arduino.cc/ ? I try to avoid that as much as possible because it seems to be a toxic community, with a number of nasty old-timers constantly berating newbies on how stupid they are.

**Comment by mkarliner** [comment]
Have you thought of Gitter? https://gitter.im/
Could I also suggest that CoroutineScheduler::loop(); could be renamed runAll to avoid the assumption I made?

**Comment by bxparks** [comment]
I'm not familiar with Gitter. I'll check it out. To be honest though, I'm ok with people using GitHub to ask questions for now. The traffic is very very low. If it ever gets popular, we can create a forum.

The problem with renaming it to `runAll()` is that it doesn't run all. It just runs one then returns. It needs to be called repeatedly, which is why it needs to be called from global `loop()`. There's a symmetry between `CoroutineScheduler::setup()` which needs to be called from global `setup()` and and `CoroutineScheduler::loop()` which needs to be called from global `loop()`.
